PRINT ~Patching UI.MENU.~
	
ACTION_IF(NOT MOD_IS_INSTALLED "setup-infinity_ui.tp2" "0") THEN BEGIN
	COPY_EXISTING ~UI.MENU~ ~override/UI.MENU~
	REPLACE_TEXTUALLY ~Infinity_SetOffset(.*'WORLD_QUICKLOOT'.*,.*0,*,.*-toolbarTop)~
	%
		if (xaALOptHideQLToolbarToggle == 1) then
			Infinity_SetOffset('WORLD_QUICKLOOT',0, -5000)
		else
			Infinity_SetOffset('WORLD_QUICKLOOT',0, -toolbarTop)
		end
	%
END

ACTION_IF(FILE_EXISTS_IN_GAME ~m_dw_oof.lua~) THEN BEGIN
	PRINT ~SCS UI.MENU modifications detected.~
	COPY_EXISTING ~UI.MENU~ ~override/UI.MENU~
	REPLACE_TEXTUALLY ~dwOnOpen('WORLD_ACTIONBAR')~ 
	%
		dwOnOpen('WORLD_ACTIONBAR')
		Infinity_PushMenu('XA_AUTOLOOT')
	%
END ELSE BEGIN
	PRINT ~No SCS changes to UI.MENU were detected.~
	COPY_EXISTING ~UI.MENU~ ~override/UI.MENU~
	REPLACE_TEXTUALLY ~Infinity_PushMenu(.*'WORLD_MESSAGES'.*)~ 
	%
		Infinity_PushMenu('WORLD_MESSAGES')
		Infinity_PushMenu('XA_AUTOLOOT')
	%
END

COPY_EXISTING ~UI.MENU~ ~override/UI.MENU~

REPLACE_TEXTUALLY ~Infinity_PopMenu(.*'WORLD_MESSAGES'.*)~ 
%
	Infinity_PopMenu('WORLD_MESSAGES')
	Infinity_PopMenu('XA_AUTOLOOT')
%

REPLACE_TEXTUALLY ~function displayHelp()~ 
%
	xa_alreplace0function displayHelp()
%

REPLACE_TEXTUALLY ~xa_alreplace0~ 
~
	-- BUBB EDIT DEBUG DUMP START

	function xaAlphanumericSortEntries(o)
	   local function conv(s)
		  local res, dot = "", ""
		  for n, m, c in tostring(s):gmatch"(0*(%d*))(.?)" do
			 if n == "" then
				dot, c = "", dot..c
			 else
				res = res..(dot == "" and ("%03d%s"):format(#m, m)
									  or "."..n)
				dot, c = c:match"(%.?)(.*)"
			 end
			 res = res..c:gsub(".", "\0%0")
		  end
		  return res
	   end
	   table.sort(o,
		  function (a, b)
			 local ca, cb = conv(a.string), conv(b.string)
			 return ca < cb or ca == cb and a.string < b.string
		  end)
	   return o
	end
	xa_alreplace1
~	
REPLACE_TEXTUALLY ~xa_alreplace1~ 
%
	function xaFillDumpLevel(tableName, levelTable, levelToFill, levelTableKey)

		local tableKey, tableValue = next(levelTable, levelTableKey)
		while tableValue ~= nil do

			local tableValueType = type(tableValue)

			if tableValueType == 'string' or tableValueType == 'number' or tableValueType == 'boolean' then

				local entry = {}
				entry.string = tableValueType..' '..tableKey..' = '
				entry.value = tableValue
				table.insert(levelToFill, entry)

			elseif tableValueType == 'table' then

				if tableKey ~= '_G' then

					local entry = {}
					entry.string = tableValueType..' '..tableKey..':\n'
					entry.value = {} --entry.value is a levelToFill

					entry.value.previous = {}
					entry.value.previous.tableName = tableName
					entry.value.previous.levelTable = levelTable
					entry.value.previous.levelToFill = levelToFill
					entry.value.previous.levelTableKey = tableKey

					table.insert(levelToFill, entry)

					return xaFillDumpLevel(tableKey, tableValue, entry.value)
				end
			elseif tableValueType == 'userdata' then

				metatable = getmetatable(tableValue)
				local entry = {}

				if metatable ~= nil then

					entry.string = tableValueType..' '..tableKey..':\n'
					entry.value = {} --entry.value is a levelToFill

					entry.value.previous = {}
					entry.value.previous.tableName = tableName
					entry.value.previous.levelTable = levelTable
					entry.value.previous.levelToFill = levelToFill
					entry.value.previous.levelTableKey = tableKey

					table.insert(levelToFill, entry)

					return xaFillDumpLevel(tableKey, metatable, entry.value)
				else

					entry.string = tableValueType..' '..tableKey..' = '
					entry.value = 'nil'
					table.insert(levelToFill, entry)
				end
			else

				local entry = {}
				entry.string = tableValueType..' '..tableKey
				entry.value = nil
				table.insert(levelToFill, entry)
			end

			--Iteration
			tableKey, tableValue = next(levelTable, tableKey)
			--Iteration
		end

		--Sort the now finished level
		xaAlphanumericSortEntries(levelToFill)
		--Sort the now finished level

		local previous = levelToFill.previous

		if previous ~= nil then

			--Clear out "previous" metadata, as it is no longer needed.
			local previousTableName = previous.tableName
			local previousLevelTable = previous.levelTable
			local previousLevelToFill = previous.levelToFill
			local previousLevelTableKey = previous.levelTableKey
			levelToFill.previous = nil
			--Clear out "previous" metadata, as it is no longer needed.

			return xaFillDumpLevel(previousTableName, previousLevelTable,
								 previousLevelToFill, previousLevelTableKey)
		else
			return levelToFill
		end
	end
	function xaPrintEntries(entriesTable, indentLevel, indentStrings, previousState, levelTableKey)

		tableEntryKey, tableEntry = next(entriesTable, levelTableKey)
		while(tableEntry ~= nil) do

			tableEntryString = tableEntry.string
			tableEntryValue = tableEntry.value
			indentString = indentStrings[indentLevel]

			if tableEntryValue ~= nil then

				if type(tableEntryValue) ~= 'table' then

					valueToPrint = string.gsub(tostring(tableEntryValue), '\n', '\\n')
					print(indentString..tableEntryString..valueToPrint)
				else
		
					print(indentString..tableEntryString)
					print(indentString..'{')

					local previous = {}
					previous.entriesTable = entriesTable
					previous.indentLevel = indentLevel
					previous.levelTableKey = tableEntryKey
					previous.previousState = previousState

					indentLevel = indentLevel + 1

					indentStringsSize = #indentStrings
					if indentLevel > indentStringsSize then
						indentStrings[indentStringsSize + 1] = indentStrings[indentStringsSize]..'\t'
					end

					return xaPrintEntries(tableEntryValue, indentLevel, indentStrings, previous)
				end
			else
				print(indentString..tableEntryString)
			end

			--Increment
			tableEntryKey, tableEntry = next(entriesTable, tableEntryKey)
			--Increment
		end

		print(indentStrings[indentLevel - 1]..'}')

		--Finish previous levels
		if previousState ~= nil then

			return xaPrintEntries(previousState.entriesTable, previousState.indentLevel, indentStrings,
								previousState.previousState, previousState.levelTableKey)
		end
	end

	function xaDump(key, valueToDump)

		valueToDumpType = type(valueToDump)

		if valueToDumpType == 'string' or valueToDumpType == 'number' or valueToDumpType == 'boolean' then

			print(valueToDumpType..' '..key..' = '..valueToDump)

		elseif valueToDumpType == 'table' then

			print(valueToDumpType..' '..key..':')
			print('{')
			entries = xaFillDumpLevel(key, valueToDump, {})
			xaPrintEntries(entries, 1, {[0] = '', [1] = '\t'})

		elseif valueToDumpType == 'userdata' then

			metatable = getmetatable(valueToDump)

			if metatable ~= nil then

				print(valueToDumpType..' '..key..':')
				print('{')
				entries = xaFillDumpLevel(key, metatable, {})
				xaPrintEntries(entries, 1, {[0] = '', [1] = '\t'})
			else

				print(valueToDumpType..' '..key..' = nil')
			end
		else

			print(valueToDumpType..' '..key)
		end
	end
	
	-- BUBB EDIT DEBUG DUMP END
	
	xa_alreplace2
%	

REPLACE_TEXTUALLY ~xa_alreplace2~ 
%	
	function xaSpaceRemaining()
		characters = {}
		Infinity_UpdateLuaStats()
		local emptySpaces = 0
		for key, character in pairs(characters) do
			local equipment = character.equipment
			for i = 0, 15, 1 do
				local groupKey = "group"..i
				local isEmpty = equipment[groupKey].empty
				if isEmpty == 1 then
					emptySpaces = emptySpaces + 1
				end
			end
		end
		return emptySpaces
	end

	-- BUBB EDIT LOOT START
	function xaDoesCharacterHaveSpace()
		characters = {}
		Infinity_UpdateLuaStats()
		for key, character in pairs(characters) do
			local equipment = character.equipment
			for i = 0, 15, 1 do
				local groupKey = "group"..i
				local isEmpty = equipment[groupKey].empty
				if isEmpty == 1 then
					return true
				end
			end
		end
		return false
	end
	function xaGetPricePerWeight(price, weight)
		if price == 0 then
			return 0
		elseif weight == 0 then
			return price
		else
			return price / weight
		end
	end

	function xaDecideWhetherToPickUp(itemRes, itemInfo)
		local weightLimitExceeded = false
		
		-- Ammunition
		local itemCategory = itemInfo.category
			-- Arrows
				if (xaALOptArrowsToggle == 1) then
					if(itemCategory == 5) then
						return true
					end
				end
			-- Bolts
				if (xaALOptBoltsToggle == 1) then
					if(itemCategory == 31) then
						return true
					end
				end
			-- Bullets
				if (xaALOptBulletsToggle == 1) then
					if(itemCategory == 14) then
						return true
					end
				end
			-- Darts
				if (xaALOptDartsToggle == 1) then
					if(itemCategory == 24) then
						return true
					end
				end
		
		-- Weight Check
		if xaALOptWeightToggle == 1 then
			if (itemInfo.weight > xaALOptWeightField) then
				weightLimitExceeded = true
			end
		end

		-- Critical Items
		if bubbALOptCriticalItemsToggle == 1 then
			if (itemInfo.critical == 1) and weightLimitExceeded then
				return true and not weightLimitExceeded
			end
		end

		-- Enchanted Weapons
		if bubbALOptEnchantedWeaponsToggle == 1 then
			if (itemInfo.enchantment >= tonumber(bubbALOptEnchantedWeaponsField)) then
				return true and not weightLimitExceeded
			end
		end

		-- Price
		if bubbALOptPriceToggle == 1 then
			if itemInfo.price >= tonumber(bubbALOptPriceField) then
				return true and not weightLimitExceeded
			end
		end

		-- Price per Weight
		if bubbALOptPricePerWeightToggle == 1 then
			if xaGetPricePerWeight(itemInfo.price, itemInfo.weight) >= tonumber(bubbALOptPricePerWeightField) then
				return true and not weightLimitExceeded
			end
		end

		return false
	end
	function xaLoadALConfig()
		
		xa_configLoaded = true
		--xa_screenWidth, xa_screenHeight = Infinity_GetScreenSize()
		bubbALOptOnToggle = 				Infinity_GetINIValue('Bubb Autoloot', 'bubbALOptOnToggle', 					0)
		xaALOptArrowsToggle =    		Infinity_GetINIValue('Bubb Autoloot', 'xaALOptArrowsToggle', 			0)
		xaALOptBoltsToggle =    		Infinity_GetINIValue('Bubb Autoloot', 'xaALOptBoltsToggle', 			0)
		xaALOptBulletsToggle =    		Infinity_GetINIValue('Bubb Autoloot', 'xaALOptBulletsToggle', 			0)
		xaALOptDartsToggle =    		Infinity_GetINIValue('Bubb Autoloot', 'xaALOptDartsToggle', 			0)
		bubbALOptCriticalItemsToggle =    	Infinity_GetINIValue('Bubb Autoloot', 'bubbALOptCriticalItemsToggle', 		0)
		bubbALOptEnchantedWeaponsToggle = 	Infinity_GetINIValue('Bubb Autoloot', 'bubbALOptEnchantedWeaponsToggle', 	0)
		bubbALOptEnchantedWeaponsField =  	Infinity_GetINIValue('Bubb Autoloot', 'bubbALOptEnchantedWeaponsField',		'1')
		xaALOptWeightToggle =             	Infinity_GetINIValue('Bubb Autoloot', 'xaALOptWeightToggle',             	'1')
		xaALOptWeightField =             	Infinity_GetINIValue('Bubb Autoloot', 'xaALOptWeightField',             	'10')
		bubbALOptGoldToggle =             	Infinity_GetINIValue('Bubb Autoloot', 'bubbALOptGoldToggle',             	0)
		bubbALOptPriceToggle =            	Infinity_GetINIValue('Bubb Autoloot', 'bubbALOptPriceToggle',            	0)
		bubbALOptPriceField =             	Infinity_GetINIValue('Bubb Autoloot', 'bubbALOptPriceField',             	'1')
		bubbALOptPricePerWeightToggle =   	Infinity_GetINIValue('Bubb Autoloot', 'bubbALOptPricePerWeightToggle',   	0)
		bubbALOptPricePerWeightField =    	Infinity_GetINIValue('Bubb Autoloot', 'bubbALOptPricePerWeightField',    	'1')
		xaALOptMenuXField =    	Infinity_GetINIValue('Bubb Autoloot', 'xaALOptMenuXField',    	'100')
		xaALOptMenuYField =    	Infinity_GetINIValue('Bubb Autoloot', 'xaALOptMenuYField',    	'100')
		xaALOptHideQLToolbarToggle = Infinity_GetINIValue('Bubb Autoloot', 'xaALOptHideQLToolbarToggle', '1')
		
		if ((bubbALOptCriticalItemsToggle == 1) or
			(bubbALOptEnchantedWeaponsToggle == 1) or
			(bubbALOptPriceToggle == 1) or
			(bubbALOptPricePerWeightToggle == 1) or
			(xaALOptWeightToggle == 1) or
			(xaALOptArrowsToggle == 1) or
			(xaALOptBoltsToggle == 1) or
			(xaALOptBulletsToggle == 1) or
			(xaALOptDartsToggle == 1))
		then
			-- Infinity_DisplayString("[Auto Loot] IC Needed = true.") 
			xa_itemCheckNeeded = true
		else
			-- Infinity_DisplayString("[Auto Loot] IC Needed = false.") 
			xa_itemCheckNeeded = false
		end
		
		--xaWriteAutolootOptions()
		--Infinity_DisplayString("[Auto Loot] Configuration loaded from INI.")
	end
	function xaPickupLoot()
		
		if (xa_iterations < 20) or (worldScreen:CheckIfPaused()) then
			xa_iterations = xa_iterations + 1
			return
		end
		xa_iterations = 0
		if (bubbALOptOnToggle == 1) and (xa_ALMenuOpen == false) then
			local spaceRemaining = 0
			if (groundItemsButtonToggle ~= 1) then 
				groundItemsButtonToggle = 1
				worldScreen:StartGroundItems()
			end
			if loot.groundItems[0] == nil then
				--Infinity_DisplayString("[Auto Loot] Nil.")
				return
			end
			
			local groundItemCount = #loot.groundItems
			
			--if (groundItemCount == 0) then
			--	Infinity_DisplayString("[Auto Loot] GI Count 0.")
			--	return
			--end
			
			if (xa_itemCheckNeeded == true) then
				spaceRemaining = xaSpaceRemaining()
				-- Infinity_DisplayString("[Auto Loot] Space Remaining:"..spaceRemaining)
			end
			
			local i = 0
			while (i <= groundItemCount)
			do
				--Infinity_DisplayString("[Auto Loot] Processing "..i.." of "..groundItemCount)
				local groundItemSlot = loot.groundItems[i]
				local groundItem = groundItemSlot.item
				local info = lootInfo[groundItem.res]
				
				-- Gold doesn't need an empty space check
				if groundItem.res == "MISC07" then 
					if (bubbALOptGoldToggle == 1) then
						Infinity_DisplayString("XA_STR_REF_110")
						worldScreen:OnGroundButtonClick(groundItemSlot.slotId, groundItemSlot.containerId, groundItem.res)
						i = i - 1
						groundItemCount = groundItemCount - 1
					end
				elseif (xa_itemCheckNeeded == true) and (spaceRemaining > 0) then
					if xaDecideWhetherToPickUp(groundItem.res, info) then
						Infinity_DisplayString("XA_STR_REF_111"..groundItem.name)
						worldScreen:OnGroundButtonClick(groundItemSlot.slotId, groundItemSlot.containerId, groundItem.res)
						spaceRemaining = (spaceRemaining - 1)
						i = i - 1
						groundItemCount = groundItemCount - 1
					end
				end
				i = i + 1
			end
		end
	end
	function xaValidateEntry(toggle, field)
		if(toggle == 1) then
			if(field == "") then
				return 0
			end
		end
		return toggle
	end
	function xaWriteAutolootOptions()
		-- Infinity_DisplayString("[Auto Loot] On Close Called.") 
		
		bubbALOptPriceToggle = xaValidateEntry(bubbALOptPriceToggle, bubbALOptPriceField)
		bubbALOptEnchantedWeaponsToggle = xaValidateEntry(bubbALOptEnchantedWeaponsToggle, bubbALOptEnchantedWeaponsField)
		bubbALOptPricePerWeightToggle = xaValidateEntry(bubbALOptPricePerWeightToggle, bubbALOptPricePerWeightField)
		xaALOptWeightToggle = xaValidateEntry(xaALOptWeightToggle, xaALOptWeightField)
	
		if ((bubbALOptCriticalItemsToggle == 1) or
			(bubbALOptEnchantedWeaponsToggle == 1) or
			(bubbALOptPriceToggle == 1) or
			(bubbALOptPricePerWeightToggle == 1))
		then
			-- Infinity_DisplayString("[Auto Loot] IC Needed = true.") 
			xa_itemCheckNeeded = true
		else
			-- Infinity_DisplayString("[Auto Loot] IC Needed = false.") 
			xa_itemCheckNeeded = false
		end
		
		Infinity_SetINIValue('Bubb Autoloot', 'bubbALOptOnToggle',               tostring(bubbALOptOnToggle))
		Infinity_SetINIValue('Bubb Autoloot', 'bubbALOptCriticalItemsToggle',    tostring(bubbALOptCriticalItemsToggle))
		Infinity_SetINIValue('Bubb Autoloot', 'bubbALOptEnchantedWeaponsToggle', tostring(bubbALOptEnchantedWeaponsToggle))
		Infinity_SetINIValue('Bubb Autoloot', 'bubbALOptEnchantedWeaponsField',  bubbALOptEnchantedWeaponsField)
		Infinity_SetINIValue('Bubb Autoloot', 'bubbALOptGoldToggle',             tostring(bubbALOptGoldToggle))
		Infinity_SetINIValue('Bubb Autoloot', 'xaALOptWeightToggle',            tostring(xaALOptWeightToggle))
		Infinity_SetINIValue('Bubb Autoloot', 'xaALOptWeightField',             xaALOptWeightField)
		Infinity_SetINIValue('Bubb Autoloot', 'bubbALOptPriceToggle',            tostring(bubbALOptPriceToggle))
		Infinity_SetINIValue('Bubb Autoloot', 'bubbALOptPriceField',             bubbALOptPriceField)
		Infinity_SetINIValue('Bubb Autoloot', 'bubbALOptPricePerWeightToggle',   tostring(bubbALOptPricePerWeightToggle))
		Infinity_SetINIValue('Bubb Autoloot', 'bubbALOptPricePerWeightField',    bubbALOptPricePerWeightField)
		Infinity_SetINIValue('Bubb Autoloot', 'xaALOptMenuXField', xaALOptMenuXField) 
		Infinity_SetINIValue('Bubb Autoloot', 'xaALOptMenuYField', xaALOptMenuYField) 
		Infinity_SetINIValue('Bubb Autoloot', 'xaALOptHideQLToolbarToggle', xaALOptHideQLToolbarToggle) 
		Infinity_SetINIValue('Bubb Autoloot', 'xaALOptArrowsToggle', xaALOptArrowsToggle) 
		Infinity_SetINIValue('Bubb Autoloot', 'xaALOptBoltsToggle', xaALOptBoltsToggle) 
		Infinity_SetINIValue('Bubb Autoloot', 'xaALOptBulletsToggle', xaALOptBulletsToggle) 
		Infinity_SetINIValue('Bubb Autoloot', 'xaALOptDartsToggle', xaALOptDartsToggle) 
	end
	
	function xaInitializeAutolootOptionsMenu()
		xaLoadALConfig()
		-- Infinity_DisplayString("[Auto Loot] On Open Called.") 
		local screenWidth, screenHeight = Infinity_GetScreenSize()
		local backgroundX, backgroundY, backgroundWidth, backgroundHeight = Infinity_GetArea('bubbALOptBackground')
		local horizontalMargin = screenWidth - backgroundWidth
		local newBackGroundX = horizontalMargin / 2
		local verticalMargin = screenHeight - backgroundHeight
		local newBackGroundY = verticalMargin / 2

		-- Background
		Infinity_SetArea('bubbALOptBackground', newBackGroundX, newBackGroundY, nil, nil)

		-- Exit Button
		Infinity_SetArea('bubbALOptExitButton', newBackGroundX + backgroundWidth - 54, newBackGroundY + 10, nil, nil)

		-- Autoloot On
		newBackGroundY = newBackGroundY + 10
		Infinity_SetArea('bubbALOptOnToggle', newBackGroundX + 10, newBackGroundY, nil, nil)
		Infinity_SetArea('bubbALOptOn',       newBackGroundX + 52, newBackGroundY, nil, nil)

		-- Ammunition
			-- Arrows
			newBackGroundY = newBackGroundY + 42
			Infinity_SetArea('xaALOptArrowsToggle', newBackGroundX + 10, newBackGroundY, nil, nil)
			Infinity_SetArea('xaALOptArrows',       newBackGroundX + 52, newBackGroundY, nil, nil)
				
			-- Bolts
			newBackGroundY = newBackGroundY + 42
			Infinity_SetArea('xaALOptBoltsToggle', newBackGroundX + 10, newBackGroundY, nil, nil)
			Infinity_SetArea('xaALOptBolts',       newBackGroundX + 52, newBackGroundY, nil, nil)
			
			-- Bullets
			newBackGroundY = newBackGroundY + 42
			Infinity_SetArea('xaALOptBulletsToggle', newBackGroundX + 10, newBackGroundY, nil, nil)
			Infinity_SetArea('xaALOptBullets',       newBackGroundX + 52, newBackGroundY, nil, nil)
			
			-- Darts
			newBackGroundY = newBackGroundY + 42
			Infinity_SetArea('xaALOptDartsToggle', newBackGroundX + 10, newBackGroundY, nil, nil)
			Infinity_SetArea('xaALOptDarts',       newBackGroundX + 52, newBackGroundY, nil, nil)

		-- Critical Items
		newBackGroundY = newBackGroundY + 42
		Infinity_SetArea('bubbALOptCriticalItemsToggle', newBackGroundX + 10, newBackGroundY, nil, nil)
		Infinity_SetArea('bubbALOptCriticalItems',       newBackGroundX + 52, newBackGroundY, nil, nil)

		-- Enchanted Weapons
		newBackGroundY = newBackGroundY + 42
		Infinity_SetArea('bubbALOptEnchantedWeaponsToggle', newBackGroundX + 10,           newBackGroundY, nil, nil)
		Infinity_SetArea('bubbALOptEnchantedWeapons',       newBackGroundX + 52,           newBackGroundY, nil, nil)
		Infinity_SetArea('bubbALOptEnchantedWeaponsField',  newBackGroundX + 52 + 356 + 5, newBackGroundY, nil, nil)

		-- Weight
		newBackGroundY = newBackGroundY + 42
		Infinity_SetArea('xaALOptWeightToggle', newBackGroundX + 10, newBackGroundY, nil, nil)
		Infinity_SetArea('xaALOptWeightLabel',       newBackGroundX + 52, newBackGroundY, nil, nil)
		Infinity_SetArea('xaALOptWeightField',       newBackGroundX + 52 + 308 + 5, newBackGroundY, nil, nil)

		-- Gold
		newBackGroundY = newBackGroundY + 42
		Infinity_SetArea('bubbALOptGoldToggle', newBackGroundX + 10, newBackGroundY, nil, nil)
		Infinity_SetArea('bubbALOptGold',       newBackGroundX + 52, newBackGroundY, nil, nil)

		-- Price
		newBackGroundY = newBackGroundY + 42
		Infinity_SetArea('bubbALOptPriceToggle', newBackGroundX + 10,           newBackGroundY, nil, nil)
		Infinity_SetArea('bubbALOptPrice',       newBackGroundX + 52,           newBackGroundY, nil, nil)
		Infinity_SetArea('bubbALOptPriceField',  newBackGroundX + 52 + 218 + 5, newBackGroundY, nil, nil)

		-- Price per Weight
		newBackGroundY = newBackGroundY + 42
		Infinity_SetArea('bubbALOptPricePerWeightToggle', newBackGroundX + 10,           newBackGroundY, nil, nil)
		Infinity_SetArea('bubbALOptPricePerWeight',       newBackGroundX + 52,           newBackGroundY, nil, nil)
		Infinity_SetArea('bubbALOptPricePerWeightField',  newBackGroundX + 52 + 308 + 5, newBackGroundY, nil, nil)

		-- Hide QL Toggle
		newBackGroundY = newBackGroundY + 42
		Infinity_SetArea('xaALOptHideQLToolbarLabel',       newBackGroundX + 10,           newBackGroundY, nil, nil)
		Infinity_SetArea('xaALOptHideQLToolbarToggle',  newBackGroundX + 52 + 308 + 5, newBackGroundY, nil, nil)

		-- Menu X
		newBackGroundY = newBackGroundY + 42
		Infinity_SetArea('xaALOptMenuXLabel', newBackGroundX + 10, newBackGroundY, nil, nil)
		Infinity_SetArea('xaALOptMenuXField', newBackGroundX + 52 + 308 + 5, newBackGroundY, nil, nil)
		
		-- Menu Y
		newBackGroundY = newBackGroundY + 42
		Infinity_SetArea('xaALOptMenuYLabel', newBackGroundX + 10, newBackGroundY, nil, nil)
		Infinity_SetArea('xaALOptMenuYField',  newBackGroundX + 52 + 308 + 5, newBackGroundY, nil, nil)
		
		-- Launcher Offset Label
		newBackGroundY = newBackGroundY + 42
		Infinity_SetArea('xaALOptMenuNoteLabel', newBackGroundX + 10, newBackGroundY, nil, nil)
	end
	
	function xaPlaceAutolootButton()
		Infinity_SetArea('XA_AUTOLOOT_BUTTON', xaALOptMenuXField, xaALOptMenuYField, nil, nil)
	end
	
	bubbALOptPausedOnOpen = false
	-- BUBB EDIT LOOT END
	xa_iterations = 0;
	xa_configLoaded = false;
	xa_ALMenuOpen = false;
%

APPEND ~UI.MENU~ 
%
	-- BUBB EDIT LOOT START
	menu
	{
		name "XA_AUTOLOOT"
		ignoreEsc
		onOpen 
		"
			xaLoadALConfig()
			xaPlaceAutolootButton()
			
		"
		label
		{
			area 0 0 -1 -1
			text lua 
			"
				xaPickupLoot()
			"
		}
		button
		{
			name "XA_AUTOLOOT_BUTTON"
			area -1 -1 48 48
			bam XAALBTN
			action 
			"
				worldScreen:StopGroundItems()
				xa_ALMenuOpen = true
				Infinity_PushMenu('BUBB_AUTOLOOT_OPTIONS')	
			"
		}
	}
	menu
	{
		name "BUBB_AUTOLOOT_OPTIONS"
		modal
		onOpen 
		"
			
			xaInitializeAutolootOptionsMenu()
		"
		onClose 
		"
			xa_ALMenuOpen = false
			xaWriteAutolootOptions()
			xaPlaceAutolootButton()
		"

		-- Background
		label
		{
			name "bubbALOptBackground"
			area -1 -1 500 650
			rectangle 0
		}

		-- Exit Button
		button
		{
			name "bubbALOptExitButton"
			bam GUIOSW
			area -1 -1 44 44
			sequence 2
			action 
			"
				Infinity_PopMenu('BUBB_AUTOLOOT_OPTIONS')	
			"
		}

		-- Autoloot On
		button
		{
			name "bubbALOptOnToggle"
			area -1 -1 32 32
			bam CBUTT
			glow lua "bubbALOptOnToggle == 1"
			scaleToClip
			action 
			"
				if bubbALOptOnToggle == 1 then
					bubbALOptOnToggle = 0
				else
					bubbALOptOnToggle = 1
				end
			"
		}
		label
		{
			name "bubbALOptOn"
			area -1 -1 200 32
			text "XA_STR_REF_100"
			text style 'normal'
			text align left center
		}

		-- Ammunition
			-- Arrows
			button
			{
				name "xaALOptArrowsToggle"
				area -1 -1 32 32
				bam CBUTT
				glow lua "xaALOptArrowsToggle == 1"
				scaleToClip
				action 
				"
					if xaALOptArrowsToggle == 1 then
						xaALOptArrowsToggle = 0
					else
						xaALOptArrowsToggle = 1
					end
				"
			}
			label
			{
				name "xaALOptArrows"
				area -1 -1 200 32
				text "XA_STR_REF_112"
				text style 'normal'
				text align left center
			}
			-- Bolts
			button
			{
				name "xaALOptBoltsToggle"
				area -1 -1 32 32
				bam CBUTT
				glow lua "xaALOptBoltsToggle == 1"
				scaleToClip
				action 
				"
					if xaALOptBoltsToggle == 1 then
						xaALOptBoltsToggle = 0
					else
						xaALOptBoltsToggle = 1
					end
				"
			}
			label
			{
				name "xaALOptBolts"
				area -1 -1 200 32
				text "XA_STR_REF_113"
				text style 'normal'
				text align left center
			}
			-- Bullets
			button
			{
				name "xaALOptBulletsToggle"
				area -1 -1 32 32
				bam CBUTT
				glow lua "xaALOptBulletsToggle == 1"
				scaleToClip
				action 
				"
					if xaALOptBulletsToggle == 1 then
						xaALOptBulletsToggle = 0
					else
						xaALOptBulletsToggle = 1
					end
				"
			}
			label
			{
				name "xaALOptBullets"
				area -1 -1 200 32
				text "XA_STR_REF_114"
				text style 'normal'
				text align left center
			}
			-- Darts
			button
			{
				name "xaALOptDartsToggle"
				area -1 -1 32 32
				bam CBUTT
				glow lua "xaALOptDartsToggle == 1"
				scaleToClip
				action 
				"
					if xaALOptDartsToggle == 1 then
						xaALOptDartsToggle = 0
					else
						xaALOptDartsToggle = 1
					end
				"
			}
			label
			{
				name "xaALOptDarts"
				area -1 -1 200 32
				text "XA_STR_REF_115"
				text style 'normal'
				text align left center
			}
		-- Critical Items
		button
		{
			name "bubbALOptCriticalItemsToggle"
			area -1 -1 32 32
			bam CBUTT
			glow lua "bubbALOptCriticalItemsToggle == 1"
			scaleToClip
			action 
			"
				if bubbALOptCriticalItemsToggle == 1 then
					bubbALOptCriticalItemsToggle = 0
				else
					bubbALOptCriticalItemsToggle = 1
				end
			"
		}
		label
		{
			name "bubbALOptCriticalItems"
			area -1 -1 200 32
			text "XA_STR_REF_101"
			text style 'normal'
			text align left center
		}

		-- Enchanted Weapons
		button
		{
			name "bubbALOptEnchantedWeaponsToggle"
			area -1 -1 32 32
			bam CBUTT
			glow lua "bubbALOptEnchantedWeaponsToggle == 1"
			scaleToClip
			action 
			"
				if bubbALOptEnchantedWeaponsToggle == 1 then
					bubbALOptEnchantedWeaponsToggle = 0
				else
					bubbALOptEnchantedWeaponsToggle = 1
				end
			"
		}
		label
		{
			name "bubbALOptEnchantedWeapons"
			area -1 -1 356 32
			text "XA_STR_REF_102"
			text style 'normal'
			text align left center
		}
		edit
		{
			name "bubbALOptEnchantedWeaponsField"
			area -1 -1 20 32
			var bubbALOptEnchantedWeaponsField
			text style "edit"
			align left center
			maxlines 1
			action
			"
				if((tonumber(letter_pressed) ~= nil
					and #tostring(bubbALOptEnchantedWeaponsField) < 1)
					or not letter_pressed)
				then
					return 1
				else
					return 0
				end
			"
		}

		-- Gold
		button
		{
			name "bubbALOptGoldToggle"
			area -1 -1 32 32
			bam CBUTT
			glow lua "bubbALOptGoldToggle == 1"
			scaleToClip
			action 
			"
				if bubbALOptGoldToggle == 1 then
					bubbALOptGoldToggle = 0
				else
					bubbALOptGoldToggle = 1
				end
			"
		}
		label
		{
			name "bubbALOptGold"
			area -1 -1 356 32
			text "XA_STR_REF_103"
			text style 'normal'
			text align left center
		}

		-- Price
		button
		{
			name "bubbALOptPriceToggle"
			area -1 -1 32 32
			bam CBUTT
			glow lua "bubbALOptPriceToggle == 1"
			scaleToClip
			action 
			"
				if bubbALOptPriceToggle == 1 then
					bubbALOptPriceToggle = 0
				else
					bubbALOptPriceToggle = 1
				end
			"
		}
		label
		{
			name "bubbALOptPrice"
			area -1 -1 218 32
			text "XA_STR_REF_104"
			text style 'normal'
			text align left center
		}
		edit
		{
			name "bubbALOptPriceField"
			area -1 -1 50 32
			var bubbALOptPriceField
			text style "edit"
			align left center
			maxlines 1
			action
			"
				if((tonumber(letter_pressed) ~= nil
					and #tostring(bubbALOptPriceField) < 5)
					or not letter_pressed)
				then
					return 1
				else
					return 0
				end
			"
		}
		-- Weight Limit
		button
		{
			name "xaALOptWeightToggle"
			area -1 -1 32 32
			bam CBUTT
			glow lua "xaALOptWeightToggle == 1"
			scaleToClip
			action 
			"
				if xaALOptWeightToggle == 1 then
					xaALOptWeightToggle = 0
				else
					xaALOptWeightToggle = 1
				end
			"
		}
		label
		{
			name "xaALOptWeightLabel"
			area -1 -1 308 32
			text "XA_STR_REF_105"
			text style 'normal'
			text align left center
		}
		edit
		{
			name "xaALOptWeightField"
			area -1 -1 50 32
			var xaALOptWeightField
			text style "edit"
			align left center
			maxlines 1
			action
			"
				if((tonumber(letter_pressed) ~= nil
					and #tostring(xaALOptWeightField) >= 0)
					or not letter_pressed)
				then
					return 1
				else
					return 0
				end
			"
		}
		
		-- Price per Weight
		button
		{
			name "bubbALOptPricePerWeightToggle"
			area -1 -1 32 32
			bam CBUTT
			glow lua "bubbALOptPricePerWeightToggle == 1"
			scaleToClip
			action 
			"
				if bubbALOptPricePerWeightToggle == 1 then
					bubbALOptPricePerWeightToggle = 0
				else
					bubbALOptPricePerWeightToggle = 1
				end
			"
		}
		label
		{
			name "bubbALOptPricePerWeight"
			area -1 -1 308 32
			text "XA_STR_REF_106"
			text style 'normal'
			text align left center
		}
		edit
		{
			name "bubbALOptPricePerWeightField"
			area -1 -1 50 32
			var bubbALOptPricePerWeightField
			text style "edit"
			align left center
			maxlines 1
			action
			"
				if((tonumber(letter_pressed) ~= nil
					and #tostring(bubbALOptPricePerWeightField) < 5)
					or not letter_pressed)
				then
					return 1
				else
					return 0
				end
			"
		}
		
		-- QL Toggle
		label
		{
			name "xaALOptHideQLToolbarLabel"
			area -1 -1 308 32
			text "XA_STR_REF_107"
			text style 'normal'
			text align left center
		}
		button
		{
			name "xaALOptHideQLToolbarToggle"
			area -1 -1 32 32
			bam CBUTT
			glow lua "xaALOptHideQLToolbarToggle == 1"
			scaleToClip
			action 
			"
				if xaALOptHideQLToolbarToggle == 1 then
					xaALOptHideQLToolbarToggle = 0
				else
					xaALOptHideQLToolbarToggle = 1
				end
			"
		}
		
		-- Menu X
		label
		{
			name "xaALOptMenuXLabel"
			area -1 -1 308 32
			text "XA_STR_REF_108"
			text style 'normal'
			text align left center
		}
		edit
		{
			name "xaALOptMenuXField"
			area -1 -1 50 32
			var xaALOptMenuXField
			text style "edit"
			align left center
			maxlines 1
			action
			"
				if((tonumber(letter_pressed) ~= nil
					and #tostring(xaALOptMenuXField) < 10000)
					or not letter_pressed)
				then
					return 1
				else
					return 0
				end
			"
		}
		
		-- Menu Y
		label
		{
			name "xaALOptMenuYLabel"
			area -1 -1 308 32
			text "XA_STR_REF_109"
			text style 'normal'
			text align left center
		}
		edit
		{
			name "xaALOptMenuYField"
			area -1 -1 50 32
			var xaALOptMenuYField
			text style "edit"
			align left center
			maxlines 1
			action
			"
				if((tonumber(letter_pressed) ~= nil
					and #tostring(xaALOptMenuYField) < 10000)
					or not letter_pressed)
				then
					return 1
				else
					return 0
				end
			"
		}
		
	
	}

	-- BUBB EDIT LOOT END
%

OUTER_SPRINT xa_100_replace @100
OUTER_SPRINT xa_101_replace @101
OUTER_SPRINT xa_102_replace @102
OUTER_SPRINT xa_103_replace @103
OUTER_SPRINT xa_104_replace @104
OUTER_SPRINT xa_105_replace @105
OUTER_SPRINT xa_106_replace @106
OUTER_SPRINT xa_107_replace @107
OUTER_SPRINT xa_108_replace @108
OUTER_SPRINT xa_109_replace @109
OUTER_SPRINT xa_110_replace @110
OUTER_SPRINT xa_111_replace @111
OUTER_SPRINT xa_112_replace @112
OUTER_SPRINT xa_113_replace @113
OUTER_SPRINT xa_114_replace @114
OUTER_SPRINT xa_115_replace @115

COPY_EXISTING ~UI.MENU~ ~override/UI.MENU~
REPLACE_TEXTUALLY ~XA_STR_REF_100~ ~%xa_100_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_101~ ~%xa_101_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_102~ ~%xa_102_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_103~ ~%xa_103_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_104~ ~%xa_104_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_105~ ~%xa_105_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_106~ ~%xa_106_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_107~ ~%xa_107_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_108~ ~%xa_108_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_109~ ~%xa_109_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_110~ ~%xa_110_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_111~ ~%xa_111_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_112~ ~%xa_112_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_113~ ~%xa_113_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_114~ ~%xa_114_replace%~
REPLACE_TEXTUALLY ~XA_STR_REF_115~ ~%xa_115_replace%~